name: 'Terratest GitHub Actions'
on:
  pull_request:
    branches:
      - master
    types: [labeled]

jobs:
  Terratest:
    name: 'Terratest'
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Terratest'
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'terratest'
          if: ${{ github.event.label.name == 'terratest' }}
          tf_actions_working_dir: '_test'

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()
