name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  complete:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/complete/'
      provider: aws
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  external_key:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/external_key/'
      provider: aws
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  external_replica_key:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/external_replica_key/'
      provider: aws
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  replica_key:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/replica_key/'
      provider: aws
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
