name: tf-checks
permissions:
  id-token: write
on:
  pull_request:
jobs:
  complete:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/complete/'
      provider: aws
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  external_key:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/external_key/'
      provider: aws
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  external_replica_key:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/external_replica_key/'
      provider: aws
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  replica_key:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/replica_key/'
      provider: aws
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
